<a href="https://colab.research.google.com/github/Tejasp9090/ML_Practice/blob/main/pandas_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data = [['Tejas',20,34000],
        ['Raj',22,44000]]
df = pd.DataFrame(data,columns=['Name','Age','Salary'])
df

    Name  Age  Salary
0  Tejas   20   34000
1    Raj   22   44000

In [3]:
data={
    'Name':["Aniket","Rahul","Priya","Sneha"],
    'Salary':[50000,60000,55000,70000],
    'Age':[25,24,26,30],
    'place':["Pune","Mumbai","Delhi","Nashik"]
}
df = pd.DataFrame(data)
df

     Name  Salary  Age   place
0  Aniket   50000   25    Pune
1   Rahul   60000   24  Mumbai
2   Priya   55000   26   Delhi
3   Sneha   70000   30  Nashik

In [4]:
df.query('Salary == 60000')

    Name  Salary  Age   place
1  Rahul   60000   24  Mumbai

In [9]:
df.query("Name.str.endswith('a')")

    Name  Salary  Age   place
2  Priya   55000   26   Delhi
3  Sneha   70000   30  Nashik